### ISSUE TITLE
项目导入到Eclipse中的时候报错：存在两个android-support-v4.jar包

### ISSUE THREAD

**Issue by WuShaojun** [qii/weiciyuan#112]
报错的日志如下，现在的版本中应该用哪个目录下的android-support-v4.jar包呢？
Found 2 versions of android-support-v4.jar in the dependency list,
but not all the versions are identical (check is based on SHA-1 only at this time).
All versions of the libraries must be the same at this time.
Versions found are:
Path: /opt/WorkSpaces/Woxingtianxia/DummyActivity/libs/android-support-v4.jar
Length: 393154
SHA-1: 307c1cc532eabbf1d135b43e5c983c9da700449d
Path: /opt/WorkSpaces/Woxingtianxia/slidingmenulibrary/libs/android-support-v4.jar
    Length: 385685
    SHA-1: 48c94ae70fa65718b382098237806a5909bb096e
 Jar mismatch! Fix your dependencies

**Comment by sharockguan** [comment]
想先测试一下作者给的Demo，但也是遇到了跟你一样的问题，而且Demo出现了一个红色感叹号，libary也是报错，为什么呢？

**Comment by sharockguan** [comment]
library没有生成jar包
