### ISSUE TITLE
[ICS]循环重启

### ISSUE THREAD

**Issue by hk3f** [qii/weiciyuan#18]
0.481，ICS系统，有时候打开apk反应很慢，然后进去之后开始自动退出，可以锁定屏幕但解锁后一直反复重启，只能关闭系统或重启系统。

这里能上传logcat么？

**Comment by easoncxz** [comment]
我估计我也遇到过。

没有仔细看上面；我遇到过的情况我不知道如何重现。「重启」是指应用连续地想打开自己；在猛按一轮home键之后能够瞥一眼主屏，但是有被吸进去应用的「启动」界面，只能看到一层半透明的膜（也就是主屏黑了，正在等应用打开，可是应用打了半天都没开）。

情况遇到不止一次，所以我才留意到了。不知道是怎么来的，但是我把它弄走的办法就是（锁了屏）等一会。

**Comment by easoncxz** [comment]
哦对了，我在我当前的v0.474之前就已经遇到过。
