### ISSUE TITLE
导入android studio的时候Error:(33, 0) Cannot invoke method minus() on null object

### ISSUE THREAD

**Issue by hloong** [qii/weiciyuan#269]
如题：
用的是1.2.1.1版本

---------------------------------
我擦，我找到解决方法了
http://stackoverflow.com/questions/19487576/gradle-build-null-console-object
第二个答案：
For some reason, running gradle in daemon mode causes a null console object. If you specify the appropriate command line flag,

./gradlew assembleRelease --no-daemon

it'll work.

**Comment by ipcjs** [comment]
上次也是报的这样的错～～

**Comment by frankfancode** [comment]
我如下修改后就可以编译运行了
versionCode - 1 改成  versionCode 1
versionName null 改成 versionName  "1.0"
两个 runProguard 改成 minifyEnabled
